### PR TITLE
Message-id validator

### LINKED ISSUE #282: Failing SwiftMailer test after upgrade to v3
Hi all, I hope this is the right place to ask this question as I couldn't immediately find something in the contributing guidelines. Appreciating if anyone could answer a question I have about a failing SwiftMailer test after upgrading to v3.

I've tried patching SwiftMailer to v3 which mostly went super smooth and didn't require any code changes (thanks!). But one test is now failing for EmailValidator v3:

https://github.com/swiftmailer/swiftmailer/blob/master/tests/unit/Swift/Mime/Headers/IdentificationHeaderTest.php#L118

With the following message:

```
1) Swift_Mime_Headers_IdentificationHeaderTest::testIdRightCanBeDotAtom
Swift_RfcComplianceException: Invalid ID given <a@b.c+&%$.d>

/Users/driesvints/Sites/swiftmailer/lib/classes/Swift/Mime/Headers/IdentificationHeader.php:183
/Users/driesvints/Sites/swiftmailer/lib/classes/Swift/Mime/Headers/IdentificationHeader.php:128
/Users/driesvints/Sites/swiftmailer/lib/classes/Swift/Mime/Headers/IdentificationHeader.php:99
/Users/driesvints/Sites/swiftmailer/tests/unit/Swift/Mime/Headers/IdentificationHeaderTest.php:118
```

The exception is being thrown here:

https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Mime/Headers/IdentificationHeader.php#L183

I guess my main question is why `a@b.c+&%$.d` isn't a valid email address anymore in EmailValidator v3? I'm not very familiar with all of the rules from RFC 2822 so I don't immediately see what's wrong here.

### PR DESCRIPTION
**Pull request by egulias**
message-id header validation according to [RFC2822 section 3.6.4](https://tools.ietf.org/html/rfc2822#section-3.6.4). This header field has some differences to an addr-spec, like not allowing comments and explicity allowing for many other charcters in the "domain part".
For message-id, parts are `id-left` @ `id-right`.

Added a new validator, refactor of internals to allow for extension.

Fixes #282 & https://github.com/symfony/symfony/pull/39685

### CODE REVIEW

**Comment by egulias** [comment]
I'd appreciate your thoughts @driesvints @derrabus , this should fix Swiftmailer & Symfony mailer needs.

File: src/MessageIDParser.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+    /**
+     * @var string
+     */
+    protected $idRight = '';
+
+    public function __construct(EmailLexer $lexer)
+    {
+        $this->lexer = $lexer;
+    }
```
Comment (derrabus) [inline src/MessageIDParser.php]: The constructor could be moved to the new `Parser` class as well.

File: src/Parser.php [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+use Egulias\EmailValidator\Result\InvalidEmail;
+use Egulias\EmailValidator\Result\Reason\ExpectingATEXT;
+
+abstract class Parser
+{
+    /**
+     * @var array
+     */
+
+    protected $warnings = [];
```
Comment (derrabus) [inline src/Parser.php]:
```suggestion
    /**
     * @var Warning\Warning[]
     */
    protected $warnings = [];
```

File: src/Parser.php [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+
+    protected function hasAtToken() : bool
+    {
+        $this->lexer->moveNext();
+        $this->lexer->moveNext();
+        if ($this->lexer->token['type'] === EmailLexer::S_AT) {
+            return false;
+        }
+
+        return true;
```
Comment (derrabus) [inline src/Parser.php]:
```suggestion

        return $this->lexer->token['type'] !== EmailLexer::S_AT;
```

**Review by derrabus — APPROVED** [review]
The new validator passes the test suite of Symfony's MIME component. Thank you! 👍🏻

**Comment by driesvints** [comment]
Awesome. I'm not sure when I'll have time to try this out but hope to soon. Thanks!

**Comment by driesvints** [comment]
Hey @egulias. I can confirm this fixes the failing test for SwiftMailer. Thanks!

I'll keep an eye out until a new release with this has been tagged and then I'll send in a patch to SwiftMailer.
